settings:
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: ROS 2
  links:
    # ROS 2 docs
    - https://github.com/ros2/ros2_documentation
    # Nav2 docs
    - https://github.com/ros-navigation/docs.nav2.org.git
    # MoveIt 2 tutorials
    - https://github.com/moveit/moveit2_tutorials.git
    # Gazebo docs
    - https://github.com/gazebosim/docs.git
